Dataset:
  - type: image
    params:
      path: Dataset
      img_shape: [28, 28 ,1]
  
  - type: stroke
    params:
      transfroms: false
  


CnnModel:
  name: SketchRecognitionCNN

  in_channels: &in_channels 1
  out_channels: &out_channels 2
  num_classes: &num_classes 75
  bias: &bias true
  
  layers:
    - type: Conv2d
      args:
        in_channels: *in_channels
        out_channels: *out_channels
        kernel_size: 3
        bias: *bias
    - type: BatchNorm2d
      args:
        num_features: *out_channels
    - type: LeakyReLU
      args:
        negative_slope: 0.1
    
    - type: Conv2d
      args:
        in_channels: *out_channels
        out_channels: 4
        kernel_size: 3
        bias: *bias
    - type: BatchNorm2d
      args:
        num_features: 4
    - type: LeakyReLU
      args:
        negative_slope: 0.1
    - type: Dropout2d
      args:
        p: 0.1

    - type: Conv2d
      args:
        in_channels: 4
        out_channels: 8
        kernel_size: 3
        bias: *bias
    - type: BatchNorm2d
      args:
        num_features: 8
    - type: MaxPool2d
      args:
        kernel_size: 2
        stride: 2
    - type: LeakyReLU
      args:
        negative_slope: 0.1
    - type: Dropout2d
      args:
        p: 0.1
    
    - type: Conv2d
      args:
        in_channels: 8
        out_channels: 16
        kernel_size: 3
        bias: *bias
    - type: BatchNorm2d
      args:
        num_features: 16
    - type: LeakyReLU
      args:
        negative_slope: 0.1
    - type: Dropout2d
      args:
        p: 0.1

    - type: Conv2d
      args:
        in_channels: 16
        out_channels: *num_classes
        kernel_size: 3
        bias: *bias
    - type: BatchNorm2d
      args:
        num_features: *num_classes
    - type: MaxPool2d
      args:
        kernel_size: 2
        stride: 2
    - type: LeakyReLU
      args:
        negative_slope: 0.1
    - type: Dropout2d
      args:
        p: 0.1

    - type: AdaptiveAvgPool2d
      args:
        output_size: 1

    - type: Flatten
      args:
        start_dim: 1
        end_dim: -1


optimizer:
  name: AdamW
  params:
    weight_decay: 5e-3
    learning_rate: 1e-2
    amsgrad: true

scheduler:
  name: ReduceLROnPlateau
  params:
    mode: min
    patience: 5

batch_size: 256
num_train: 
num_val:
num_test: 
 